// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleBody: typeof import('./src/components/main/Article/ArticleBody.vue')['default']
    ArticleCard: typeof import('./src/components/main/Article/ArticleCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/main/Header/Header.vue')['default']
    Index: typeof import('./src/components/main/Index.vue')['default']
    ManagePanel: typeof import('./src/components/manage_panel/ManagePanel.vue')['default']
    ManagePanelLogin: typeof import('./src/components/manage_panel/ManagePanelLogin/ManagePanelLogin.vue')['default']
    ManagePanelMain: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain.vue')['default']
    ManagePanelMainAbout: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain-about.vue')['default']
    ManagePanelMainEnvs: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain-envs.vue')['default']
    ManagePanelMainLinks: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain-links.vue')['default']
    ManagePanelMainOthers: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain-others.vue')['default']
    ManagePanelMainSettings: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain-settings.vue')['default']
    ManagePanelMainStatus: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain-status.vue')['default']
    ManagePanelMainSwitchdb: typeof import('./src/components/manage_panel/ManagePanelMain/ManagePanelMain-switchdb.vue')['default']
  }
}
