/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleBody: typeof import('./src/components/main/Article/ArticleBody.vue')['default']
    ArticleCard: typeof import('./src/components/main/Article/ArticleCard.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/main/Header/Header.vue')['default']
    Index: typeof import('./src/components/main/Index.vue')['default']
  }
}
